### ISSUE TITLE
Projects are being displayed in standard HTML format

### ISSUE THREAD

**Issue by sampreets3** [sampreets3/sampreets3.github.io#1]
The individual projects are not being displayed in the standard markdown styling as the rest of the webpage. Instead, they are being displayed in native HTML. Maybe I have done some error in configuring the webpage. If anyone can take a look and fix the issue, it would be of great help.

**Comment by Guilyx** [comment]
In _config.yml, starting from line 188 : 

```
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
comment: true
```

You have to add _project to the path in order for it to be parsed by the md parser. Test this and let me know. 

Add this with "project" as type. If it doesn't work try with "publications" as type.

```
  # _project
  - scope:
      path: ""
      type: project
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
```

Let me know.
